### PR TITLE
add ESP8266 support

### PR DESCRIPTION
**Pull request by kuwatay**
I added ESP8266 support. 
It worked with minimum modification.
I tested on Arduino IDE with 'examples/01_BasicUsage/01_BasicUsage.ino'

### CODE REVIEW

**Comment by smdn** [comment]
Thanks for the PR!

Would you please confirm or report that the other examples can be compiled without error?
If all examples can be compiled without any problem, I will merge this PR and will release new version.

**Comment by kuwatay** [comment]
thank you for your comment. I changed all examples can be compiled w/o error. Note that example3 use three ADC but ESP8266 has only one. I assign A0, A0+10, A0-10 for original labels.

**Comment by smdn** [comment]
Thank you for the modification of example codes. That's very helpful!

Please also push a commit which reverts the changing of `VERSION`.

**Comment by kuwatay** [comment]
here comes.

**Comment by smdn** [comment]
Ah, that's not what I meant.
What I want to say was "keep the version string, do not change it".

Ok, anyway I will fix them after merging.

**Comment by smdn** [comment]
Released new version [v1.0.3](https://github.com/smdn/PseudoMuninNode/releases/tag/v1.0.3)

Thank you for your contribution!

**Pull request merged**
